apiVersion: v1
appVersion: 1.0.2
description: Wavefront Remote Storage Adapter for Prometheus
name: prometheus-storage-adapter
version: 0.1.2
keywords:
- metric
- monitoring
- observability
- alerting
- adapter
home: https://www.wavefront.com
sources:
- https://github.com/wavefrontHQ/prometheus-storage-adapter
maintainers:
- name: josephgee
  email: jgee@vmware.com
- name: mmichael
  email: mamichael@vmware.com
